### ISSUE TITLE
Notes on GLM an Introduction doc

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/nemos#147]
Hi all I'm just going through all the demo stuff and taking notes to pester you. 😄 Starting with the Intro to GLM.

**GLM an intro notes** 
https://nemos.readthedocs.io/en/latest/generated/background/plot_00_conceptual_intro/

Many people will be going to this page as their *very first exposure* to GLMs, including lots of experimentalists. So I'm reading it with that mindset.  Overall, _this is great_. It's intuitive what is happening, and I really like how you explain the three operations. It's very well done. The explanation at the end of how you compare your model to the data is really nice too!

I have a few minor comments/questions.

1.  LNP vs GLM
    One worry I have is that from reading this, beginners might come away thinking that the GLM is just the LNP model. I might add something discussing what you'd need to add to the picture here to make a true GLM. Is it the spike history filter? If so, then maybe something like Figure 11.5B from Neuronal Dynamics: https://neuronaldynamics.epfl.ch/online/Ch11.S2.html

![lnp_vs_glm](https://github.com/flatironinstitute/nemos/assets/6643322/969d54ac-2464-436b-9268-12ca4c05126e)

2. "to make this plot work well, keep this to three values"

    Does three 'values' mean three different neurons? Three trials? Also, what are the spike count targets? What is this supposed to be? Is there an experiment, or is this simulated data to make a conceptual point. The sausage is made in the `lnp_schematic` function, so I'd explain a bit more. Experimentalists reading this will appreciate details about what this example is supposed to be showing. In particular, is there a target spike count here -- at the end you nicely discuss measuring goodness of fit using log likelihood, but we don't see this in action.

3. The aside on affine transformation   

    I know it will drive you crazy to cut it because it's accurate and the math details are important. But beginners won't care, and computationalists will cut you some slack because they know that people talk like this. I'd consider calling it a "technical aside" or something so people know they can skip it. Or...just cut it. 😅

**Comment by ahwillia** [comment]
Thanks Eric, this is very helpful. A quick comment on the "LNP vs GLM" distinction... A GLM is a broad class of models, and an LNP is one example of a GLM. The Neural Dynamics chapter / link you sent is unfortunately quite confusing on this point.

Wikipedia summarizes a GLM as any model with the following three components. By this measure *both* the LNP and GLM models in the diagram are GLMs.

<img width="876" alt="image" src="https://github.com/flatironinstitute/nemos/assets/636625/39ef47b4-1b57-449d-9754-7c13d67250ed">

Perhaps we should have a Venn diagram where GLM is a big circle and LNP (also known as "Poisson regression") is a circle or point contained within the GLM circle.

**Comment by EricThomson** [comment]
Thanks Alex that's helpful, and I was a bit confused in my thinking there: these things are *all* GLMs. The LNP is a GLM. Wrapping in a spike history filter is just adding some more params to the GLM (or you could say the LNP has a spike history filter with all the weights locked at zero I guess).  Same when you include the coupling filter params.

I'm not sure if it is worth it or not to mention in this doc, but my *hunch* is it is. Because people will be curious about the connection of LNP to the canonical Pillow GLM pic (this is from Field, adapted from Pillow):

![field_2020_glm_cartoon](https://github.com/flatironinstitute/nemos/assets/6643322/c12cb065-16b6-404d-88eb-e38d9ef86699)

Then maybe do something like what Alex suggested, and show the Pillow model as a subset of GLM's in the Nelder/Wedderburn sense (though the connection to GLMs more generally is a heavier lift). This can be a *very* confusing set of relations, and it would be sort of helpful to just get it sorted out in one place in nemos. 

If this sounds interesting I could work on a simple description of this (though I would probably need help on the last step with the connection to GLMs considered most abstractly, I think I remember Pillow discussing this in a lecture and making it clear once I would have to go clear those cobwebs and would definitely need a fact checker 😄 ).

**Comment by ahwillia** [comment]
I think this would be a great addition!

**Comment by BalzaniEdoardo** [comment]
Thanks Eric and Alex!

I double what Alex was saying about LNP being a specific instance of a GLM model. 

@EricThomson, it would be awesome If you worked on improving the intro note!

**Comment by BalzaniEdoardo** [comment]
I love the idea of a consistent graphic that guides you through the tutorials. If you check out the `index.md` in the docs folder, we have to diagrams in svg, one with the LNP, one with the recurrently connected one. If you use those svgs as the template for your diagrams we can keep it consistent with the landing page too. 

With @gviejo we were thinking of having one of those diagram at the beginning of each tutorial.

**Comment by EricThomson** [comment]
Sounds great I'll work with those images.
