### ISSUE TITLE
Notes on Fit injected current demo (dev branch)

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/nemos#149]
Overall this is great, not a lot of comments that aren't just cosmetic. The way I'm approaching this one is pretending it's my first attempt to start really digging in with nemos after going over the general intro demo (this is not hard to pretend, it's pretty much my case). And I'm coming with mindset of an experimentalist who wants to use nemos who knows their way around Python, but doesn't have much familiarity with pynapple yet. 

A few minor notes.

1. At one place it says "throughough this workshop". It also says "the dataset contains several different pynapple objects, which we discussed earlier today." This  maybe just amend to "which we will show how to use soon."

2. >  For now, the only possible observation model is the Poisson, though this may change in future releases. They can be found within nemos.observation_models.

    Now there are Gamma distributions right? So this can be amended.

3. There are some very minor heading glitches (e.g., the heading for `generate and examine model predictions` is wonky for me). So I'd amend to fix those. 

But overall this is great and I don't really have much to say. :100: 

If my suggestions above sound good I can make a PR soon.

**Comment by billbrod** [comment]
Thanks Eric! Yes, we should definitely change the things you mentioned in points 1 and 2. For point 3: those aren't actually headings, but they're the remains of notes that I used during the workshop, which we forgot to remove. If you look at the raw `.py` file (`docs/neural_modeling/plot_01_current_injection.py`), you'll see that those points are wrapped in some html, `<div class="notes">`. They should just be deleted.

Do you want to open a PR making these changes? I can also do so.

**Comment by EricThomson** [comment]
Billy thanks for the clarification on some of those headers I can check out the raw `py` files to see the intent :smile: I can work on a PR and then you can maybe help in review?

**Comment by billbrod** [comment]
That sounds great! Just ping me when you open the PR
