### ISSUE TITLE
Notes on fit calcium imaging demo

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/nemos#151]
This is a great addition, and impressive that you added it so quickly!

I would suggest adding details about the fluorophore (e.g., gcamp6f?) and its kinetics, so we have a better sense of what we are recording here. When we load the calcium traces, I would probably add a few plots of the raw traces just to give people a sense of what the raw data look like (about half of users will have strong intuitions for ephys, but not optical phys, so I think just giving them a view of the slow time course etc will be useful).

Generally, this notebook marks a pretty major shift in the GLM theory from the LNP backbone we have been following until now. I guess it's now an LNG model :man_shrugging:  Previous notebooks take quite a bit of time to explain conceptual transitions additions. I think this deserves a bit of space. E.g. currently there is:

> Since the transients are non-negative, we will use a Gamma distribution from nemos with a soft-plus non linearity.

I think _way_ more is going to be needed to massage intuitions about what exactly is happening in the shift from Poisson to Gamma.  For example, something like:

- Everything up to this is still the same, but we are adding a new noise/observation model. 
- Need continuous distribution because we are no longer modeling a count process.
- Previously we interpreted the output of the linking function as mean firing rate now we interpret it as mean calcium signal and we use it to generate a noisy signal on top of that. We can't use Gaussian because Gaussian has negative values. 

*Something* like that -- that's just me spitballing not finished or good. :laughing: 

I think it would help to plot, like in the intro to GLM with LNP case, the output of the rate estimate, and then the output of the Gamma observation model, so people can visualize how the operations work with these continuous signals. 

We should probably add R^2 for the linear regression vs GLM, it's hard to compare them by just looking. 

In general, while this is promising, it would help to have a discussion of why the results are so far off sometimes (there are clear false positive and false negative calcium signals). I'm not sure what needs to be added to it to improve accuracy? Gamma params need some further constraints? Coupling params needed? Maybe it's better for high SNR units (it's not too hard to calculate SNR from Ca  traces -- I wonder if it would be better for 2p data which has better SNR). 

Anyway those are my initial thoughts this seems very cool and an impressive addition to nemos! It is concerning that the results are so similar to linear regression. A lot to chew on here.

Sorry I'm getting tired but I can tweak it with a PR in some of the ways above, and put in little notes where I would need help or am unsure of things.

**Comment by BalzaniEdoardo** [comment]
Hei Eric, this is great feedback.  I wonder if you want to open a PR improving the flow of the notebook with your suggestions, specifically spelling out the differences between the Poisson and the Gamma model.

For the R^2 values, we should keep in mind that the linear regression is minimizing directly the mean squared error, so in the training set it may have higher scores, but also, I never did that, so we should try and see.

I agree that the linear regression is similar to the glm, this is not entirely unexpected. The advantages of the gamma are the positiveness. If one wants to simulate an firing rate, enforcing positivity is what you want. If the scale is held constant (which we assume), the Gamma, has a similar property to the Poisson model, i.e. the relation between the mean and the variance is linear.

This assumption is generally true for the spike count variability, does it hold also for calcium traces? 

If so, we can come up with an example in which the assumption is important to estimate well the parameters, and show that a linear regression could may perform poorly

**Comment by EricThomson** [comment]
Thanks Edoardo -- let me start a PR this weekend and start with some of the easier changes and some of the tougher ones I'll at least put some placeholders in where I might need some help moving them forward.

**Comment by BalzaniEdoardo** [comment]
Sounds good! 👍
