### ISSUE TITLE
Change installation instruction for developers

### ISSUE THREAD

**Issue by BalzaniEdoardo** [flatironinstitute/nemos#174]
**Is your feature request related to a problem? Please describe.**
Developers that are not core should fork the repo.

**Describe the solution you'd like**
Describe the new process for contributing

**Comment by billbrod** [comment]
Potentially helpful: the instructions that Eric and I wrote for [Caiman](https://github.com/flatironinstitute/CaImAn/blob/main/CONTRIBUTING.md#caiman-contributors-guide-hammer) and [plenoptic](https://github.com/LabForComputationalVision/plenoptic/blob/main/CONTRIBUTING.md#contributing-to-the-code), respectively

**Comment by BalzaniEdoardo** [comment]
Clos

**Comment by BalzaniEdoardo** [comment]
Closed with #196
