### ISSUE TITLE
pre-defined range/knots for basis

### ISSUE THREAD

**Issue by wulfdewolf** [flatironinstitute/nemos#178]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to be able to define a spline basis over a fixed range, instead of over the range of the given data.
For example, in [Hardcastle et al. (2017)](https://linkinghub.elsevier.com/retrieve/pii/S0896-6273(17)30237-4), fixed ranges of position, speed, head direction, and theta phase are imposed.
Ultimately, this allows for learning 'model-derived' tuning curves that are defined across the same range, as in some sessions, animals do not sample all bins.

**Describe the solution you'd like**
A simple solution would be to allow passing an absolute min and max when initialising the basis such that those are used to define the knots.
Another option is to simply allow passing the knots themselves.

**Describe alternatives you've considered**
Alternatives for me would be to integrate scikit-learn basis transformers into the nemos code, as they allow the passing knots.
They have no API for making multiplicative bases though, which I find very handy.

**Comment by BalzaniEdoardo** [comment]
Thanks for the suggestion, we'll work on it!

Do you have suggestions on how to handle out-of-bounds observations if users passes the min-max? 

My inclination would be to return NaNs for out of bound values (instead of zero, which would create artifactual jumps in the firing rate).

**Comment by wulfdewolf** [comment]
NaNs would indeed be good!
Typically, I would have bounded the data already (or it just is impossible for actual acquisition to go beyond the range).
So in practice, it should not happen often that these out of bounds occur but NaNs seem like the correct way to handle when they do.

**Comment by BalzaniEdoardo** [comment]
Closed with PR #191
