### ISSUE TITLE
add `get_params()` tests

### ISSUE THREAD

**Issue by clewis7** [flatironinstitute/nemos#185]
Want to make sure that we maintain compatibility with `sklearn`, should add some tests that make sure `get_params()` returns expected values:

1. for observation_model: the inverse link function is the only one
2. for regularizer: the regularizer strength mostly
3. for glm, it should find both regularizer and observation models and their parameters (inverse link func, and reg strength).

**Comment by BalzaniEdoardo** [comment]
Test added
