### ISSUE TITLE
do not run CI on draft PRs

### ISSUE THREAD

**Issue by clewis7** [flatironinstitute/nemos#190]
@BalzaniEdoardo thoughts on only having the CI run for PRs that are not draft

I canceled most of my CI runs while doing the latest PR, but I think it is nice not to worry about it. Also, you only get a certain number of free CI minutes per month.

**Comment by BalzaniEdoardo** [comment]
I thought at some point I disabled the ci for drafts. I totally agree it would not run

**Comment by billbrod** [comment]
Just as a note, I'm not sure we do have a limit on the number of free CI minutes per month: "GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage for use with GitHub-hosted runners, depending on the account's plan." ([source](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions)). 

There is a limit on the total execution time of each job and total concurrent jobs, but I don't think we're anywhere near those limits.

Not a bad idea to disable them for drafts anyway, but wanted to clarify (this has come up for our other packages as well).

**Comment by clewis7** [comment]
I just brought it up because Kushal and I are paying for additional minutes every month because our CI takes so long to run, so we try to make sure that the CI is not run until code is actually ready for review :)
