### ISSUE TITLE
more extensive contributing guide

### ISSUE THREAD

**Issue by clewis7** [flatironinstitute/nemos#196]
@BalzaniEdoardo What do you think about extending the contributing guide to include step-by-step instructions on how to contribute (e.g. forking or checking out a new branch from `developement`, making sure to lint, adding tests to make sure code coverage remains the same, etc.)?

**Comment by BalzaniEdoardo** [comment]
Yep, we should have a contributing guide!

**Comment by billbrod** [comment]
You can see what [I've written for plenoptic](https://github.com/LabForComputationalVision/plenoptic/blob/main/CONTRIBUTING.md) and [Eric wrote for Caiman](https://github.com/flatironinstitute/CaImAn/blob/main/CONTRIBUTING.md) as sources/inspiration!

**Comment by BalzaniEdoardo** [comment]
Closed with #198
