### ISSUE TITLE
GPU Memory allocation

### ISSUE THREAD

**Issue by davidgwyrick** [flatironinstitute/nemos#208]
**Describe the bug**
I installed the jax GPU-accelerated version of NeMoS, no errors. Upon importing nemos into my python script, the GPU has 18Gb of memory used by the program. No GLM fits have been done. Just loading the nemos module causes this.

**Screenshots**
![image](https://github.com/user-attachments/assets/f62b6191-7c27-4e76-9074-c8ad2c46f122)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by davidgwyrick** [comment]
ok I think this is a Jax issue, but I'm not sure how to solve it. I thought I installed all the drivers / cuda / jax properly but perhaps there's a compatibility issue.

**Comment by BalzaniEdoardo** [comment]
Hi David,
That's JAX, it is not a real issue. JAX allocates memory as soon as you perform any computation. In nemos, there is a pre-computation at the import.
You can control JAX memory allocation behaviore by setting a few environment variables:

```python
import os  
# Disable preallocation of GPU memory by JAX
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'

# Set JAX to allocate 50% of the available GPU memory
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = '0.5'

# Enable memory growth behavior (similar to TensorFlow), where memory is allocated as needed
os.environ['XLA_PYTHON_CLIENT_ALLOCATOR'] = 'platform'
```

**Comment by davidgwyrick** [comment]
i see. so running 2 jax programs was problematic. Thank you! I was fearful there was something wonky with my GPU / driver / cuda install and I didn't want it to be true.
