### ISSUE TITLE
Package name?

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/nemos#24]
Needs to be decided before we're up on pypi, because it's hard to change after that. 

Top choice: `scikit-neuro` / `scikit-neural` / `scikit-neuron`. Only concern: scikit stands for "scipy toolkit" (originally) and we're not actually relying on scipy that much, nor do we have any formal connection to scikit learn. Not sure that matters though

Otherwise, potential keywords to include: systems, neuro/neuron/neural/neuroscience, analysis, package/library/platform, python, data, iron (flatiron? like ironclust), rock (rock solid? foundational analyses that can be built on and compared to), basis, activity (neural activity).

Don't want: spiking (will want to be able to handle voltages and calcium as well), GLM (want to have flexibility to include other approaches), convex (will have non-convex analyses as well)

We're linking stimuli and connectivity to neural activity, anything there?

Other possibilities, with criticisms: 
- SNAP / SNAPPy (systems neuroscience analysis package / in python): [snap](https://snapcraft.io/) is a package manager for linux
- SNAiL (systems neuroscience analysis library): sounds slow
- PASND / PLASND ("peasant" / "pleasant", package / platform for analysis of systems neuroscience data): unwieldy

**Comment by gviejo** [comment]
- pynalib (python neural analysis library): very close to pynapple I know.
- neuroforge : like sourceforge

**Comment by billbrod** [comment]
- `neurobase`

**Comment by gviejo** [comment]
Neurowork (like mathwork)
Neurofield
NeuroToolBox
Neuroverse

**Comment by BalzaniEdoardo** [comment]
final decision, nemos!
