### ISSUE TITLE
Write GLM tutorial / introduction

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/nemos#4]
We'll want a gentle conceptual introduction to GLMs as part of our documentation. Jonathan Pillow has an existing one (in [python](https://github.com/pillowlab/GLMspiketraintutorial_python), and [matlab](https://github.com/pillowlab/GLMspiketraintutorial)), so we might be able to just point people to that or adapt it to our purposes (or both).

**Comment by BalzaniEdoardo** [comment]
GLM intro: `nemos/background/plot_00_conceptual_intro.py`
