### ISSUE TITLE
pseduo-r2 null model

### ISSUE THREAD

**Issue by BalzaniEdoardo** [flatironinstitute/nemos#61]
In the pseudo-r2 we are currently using the empirical mean of the observation as the Poisson null-model mean. 
More strictly, the null model is a glm with only the intercept term, if we prefer to estimate the null model by maximum likelihood we could do:

```python
        # Assuming an invertible link, the root is unique
        numeric_inverse = lambda intercept: y.mean(axis=0) - self.inverse_link_function(intercept)
        intercept_init, _ = jaxopt.ScipyRootFinding(
            method="hybr", 
            optimality_fun=numeric_inverse
        ).run(jnp.log(y.mean(axis=0)))

        # fit a model with only the intercept
        loss = lambda intercept: self.negative_log_likelihood(
            self.inverse_link_function(intercept) * jnp.ones(y.shape),
            y
        )
        null_mu = self.inverse_link_function(jaxopt.GradientDescent(loss).run(intercept_init)[0])
```

The first term is using the empirical mean to get a starting point for the ML estimation. the second step fits the intercept, then compute the mean of the null by inverting the link function. 

Is this an overkill or should we implement it?

 The first step may be used to find the initial parameters of the model (currently we are using `log(mean(count))`)

**Comment by ahwillia** [comment]
Maybe I'm missing something very basic, but it isn't obvious to me why `ScipyRootFinding` is necessary here since the the MLE of the rate parameter for a Poisson distribution is the sample mean of the observations?

**Comment by BalzaniEdoardo** [comment]
yep, that's true, definitely for Gaussian and Poisson models. Is it true for any exp. family? 

I checked it and it holds for the Gamma too, if it holds for most/all exp family we think to include, I can keep the code as is. 

Otherwise, I will have a compute null-model likelihood method that is observation distribution-specific

**Comment by ahwillia** [comment]
For exponential families the MLE corresponds the choice of parameter such that the expected sufficient statistics equal the observed sufficient statistics. https://stats.stackexchange.com/questions/111759/exponential-family-observed-vs-expected-sufficient-statistics

This works out nicely for the case of Gaussian, Poisson, Gamma, and Bernoulli. Off the top of my head I'm not immediately sure of cases where the relation is more complex.

**Comment by ahwillia** [comment]
As long as one of the sufficient statistics is the identity `t(x) = x` you will have that the mean of the distribution given by the MLE equals the empirical mean of the data. If there are additional sufficient statistics (e.g. Gaussian and Gamma which have a dispersion/variance parameter in addition to the mean) we typically assume those are somehow fixed in the context of a GLM (e.g. we fit assuming Gaussian noise with known/constant variance). So I think it is safe to keep the code as is.

**Comment by BalzaniEdoardo** [comment]
for the gamma, and probably in general, for all the densities in which the dispersion parameter is  a multiplicative factor for the log-likelihood  (if assumed fixed, but for the null-model it is fixed), it still works out fine. 
I think for most of the standard exp family it works out
