### ISSUE TITLE
Note on likelihood vs pseudo-R^2

### ISSUE THREAD

**Issue by BalzaniEdoardo** [flatironinstitute/nemos#62]
this is all good info, but probably too much for the docstring. It probably belongs in the docs somewhere, and then referenced from here. If it's not clear where in the docs right now, let's create an issue.

_Originally posted by @billbrod in https://github.com/flatironinstitute/nemos/pull/41#discussion_r1399651720_

**Comment by billbrod** [comment]
This will be part of #58
