### ISSUE TITLE
High-level pynapple interface

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/nemos#65]
Some pseudo-code for high-level pynapple-depedent interface:

```python
designer = nemos.magic_design(spike_times, epoch, # epoch is the interval set which defines trial structure
                              bin_size, time_units='s')
designer.add_coupling(connection_type, # "all-to-all", "self-only", or a matrix
                      instantiated_basis,
                      window_size,
                      time_units,
                      )
designer.add_conv_feature(feature_tsd, instantiated_basis, window_size, time_units)
designer.add_eval_feature(feature_tsd, instantiated_basis)
# X and y are pytrees
X, y = designer.construct()
glm = nemos.GLM()
glm.fit(X, y)
```

For teaching, want to start with just the following lines:
```python
designer = nemos.magic_design(spike_times, epoch, # epoch is the interval set which defines trial structure
                              bin_size, time_units='s')
designer.add_coupling()
X, y = designer.construct()
glm = nemos.GLM()
glm.fit(X, y)
```

Look at the output, figure out how to tweak the variables of coupling in order to improve, then realize we need to add more predictors, etc.

**Comment by billbrod** [comment]
`designer` should be able to return pynapple objects for each predictor, which preserves the time

**Comment by billbrod** [comment]
@gviejo : we should get rid of the `designer.construct()` step -- we should be constructing the design matrix iteratively as we add predictors, and it's always accessible as an attribute: `designer.design_matrix`

**Comment by billbrod** [comment]
Also just realized: it's a bit confusing that `add_eval_feature` is the only method that doesn't accept something time-related. We'll have to think about how to present that / explain it.

There are two time-related concepts that are necessary for converting the pynapple time series objects to the design matrix: duration and resolution. For the initialization, duration comes directly from the time index, and the user has to specify the duration. For `add_eval_feature`, duration and resolution are both grabbed from initialization, no further specification needed. For `add_coupling` and `add_conv_feature`, resolution is grabbed from initialization, but duration has to be specified. I'm not sure if it would be more or less clear to make it explicit that we're dealing with two different time concepts, but wanted to write it out here.

**Comment by billbrod** [comment]
should be able to call `designer.add_feature` and broadcast to all neurons or `designer[n].add_feature` to add to a single neuron. Ideally be able to slice into designer is well: `designer[n:n+2].add_feature` as well as list of indices: `designer[[n, i, j]].add_feature`. Make sure can interface cleanly with pynapple metadata so you can e.g., set one feature for all interneurons, potentially 
```python
x = nap.TsGroup(...)
idx = x.get_by_category(col_name)[val_name].keys() # or .index?
designer[idx].add_feature
```

**Comment by BalzaniEdoardo** [comment]
With the new basis constructor, this may be not necessary anymore
