### ISSUE TITLE
Single-neuron GLM

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/nemos#91]
Following [Feb 2024 workshop](https://github.com/flatironinstitute/nemos-workshop-feb-2024/) (which will have a draft of this), should rewrite the current GLM model to operate on single neuron, because your answer will be the same, it's (numerically) easier to fit, and it allows for different per-neuron regularizations.

Right way to do this is probably to rethink how we handle the `_check_*` methods. They currently live in `BaseRegressor` and are inherited along with that, but could move them out to be helper functions in separate `validate.py` file and have `BaseRegressor` just have a separate abstract `_validate` method which each subclass must instantiate, using the appropriate validate functions. If doing this, need to split them up some more too.

Additionally: 
- Will need to provide helpers to group together single-neuron GLMs after the fact for postprocessing (largely score and predict). Single object that takes list of fit GLMs with identical number of features and observation_model at initialization?
- will need to decide whether we should have multi-neuron model at all right now. there are models where it will matter, but we could wait until they come up rather than trying to engineer in advance
- will need to provide guidance on parallelization / how to use the single-neuron GLMs to fit a full population: for loop? list comprehension? `jax.tree_map`?

**Comment by billbrod** [comment]
For combining across neurons, that's what #109 is for. So we're leaning towards having two separate classes, with same API, just differing in the dimensionality of inputs. As discussed so far, `PopulationGLM` will do the fitting and everything, so do we also want to provide helpers to combine single-neuron GLMs if people fit them separately? Or, probably, some easy way of initiating `PopulationGLM` from already-fit single-neuron GLMs. So maybe there's two separate initialization methods? Or a helper function that accepts `*glms` and returns `PopulationGLM` (this could ideally combine `PopulationGLM` objects with each other or single-neuron GLMs as well)? Ideally, avoid an extra class for handling this. Should ensure some things are the same: observation model, definitely, but is there any other validation to run? 

Then, in documentation, we:
- introduce single-neuron GLM first
- say that, for multiple neurons, can either fit them separately and combine (easier to configure if there are lots of differences in optimization) or use `PopulationGLM` (simpler to get going, requires more standardization?). 

Questions:
- names of objects? Is `GLMPopulation` and `GLM` confusing? Should it be `GLMSingle` or something for single-neuron? I feel like it's better for them to start with same name for auto-complete reasons (like the raised-cosine basis objects), but it doesn't sound as natural.
- Validation: these should all be moved out of `base.py` and broken up so they test a single thing. Then `BaseRegressor` (or maybe `Base`?) should have an abstract `_validate` method, which should be called in `fit`, `predict`, `score`? If we wanted to be fancy could probably use a decorator for this (only need to run at beginning of function, not aftewards), but that might be overkill. Might need separate validation methods for each of the public method. Maybe can use a variety of decorators, like:
    ```python
    @validate.check_dims(X, 3)
    @validate.check_dims(y, 2)
    @validate.check_consistency(X, y)
    def fit(X, y):
    ...
    ```
   then it's very clear to developers which validation gets run (doesn't require looking at separate place in code), and it's easy to mix-and-match. maybe can configure mkdocs to document the decorators somehow ([this](https://github.com/mkdocstrings/mkdocstrings/issues/543) is relevant issue)?

**Comment by billbrod** [comment]
Actually, pydantic might be the way to handle this: https://docs.pydantic.dev/2.0/

**Comment by BalzaniEdoardo** [comment]
I would keep it simple for now and not adopt pydantic immediately. I foresee issues with schemas based on annotation and the use of pytrees. 

Example: we would like to performs checks on leaves but we may want to accept any treee struct containing the data. 

It may be possible to use pydantic but it requires a bit more thought. We have the short term priority of restructuring our GLM class by April 2024.  I would start by adding a separate validation script that gets the job done, and then discuss if and how to rely on pydantic later on.
